---
  - name: Ensure Grafana is running
    ansible.builtin.service:
      name: grafana-server
      state: started
  - name: Download nvidia_exporter.go
    get_url:
      url: https://raw.githubusercontent.com/0xVires/livepeer-grafana-monitoring/main/nvidia_exporter.go
      dest: /tmp
      #name: "{{ nvidia_exporter_system
      #group: "{{ nvidia_exporter
      #mode: 'u=rwx,g=rx,o=x'
    register: _download_binary
    until: _download_binary is succeeded
    retries: 5
    delay: 2
    check_mode: false 
  - name: Create the nvidia_exporter groups
    group:
      name: nvidia_exporter
      state: present

  - name: Create the nvidia_exporter user
    user:
      name: nvidia_exporter
      group: nvidia_exporter
      shell: /usr/sbin/nologin 

  - name: go build nvidia_exporter 
    command: /usr/local/go/bin/go build -o /tmp/nvidia_exporter /tmp/nvidia_exporter.go
    args:
      chdir: /tmp/
      creates: /tmp/nvidia_exporter
      
  - name: copy the nvidia_exporter binary to its destination
    copy:
      src: /tmp/nvidia_exporter
      dest: /usr/local/bin/
      remote_src: yes
      mode: 0744
      owner: nvidia_exporter
      group: nvidia_exporter

  - name: install service script
    copy:
      src: templates/nvidia_exporter.service.j2
      dest: /etc/systemd/system/nvidia_exporter.service
      owner: root
      group: root
      mode: 0644
    tags: systemd
  - name: reload nvidia_exporter.service
    systemd:
      name: nvidia_exporter.service
      daemon_reload: true
    tags: systemd
  - name: enable the service
    systemd: 
      name: nvidia_exporter.service
      enabled: true
    tags: systemd
  - name: start service
    systemd:
      name: nvidia_exporter.service
      state: started
    tags: systemd